### ISSUE TITLE
Replace NUnit tests with xUnit

### ISSUE THREAD

**Issue by PureKrome** [YUICompressor-NET/YUICompressor.NET#23]
Date check - (end of 2016).

sif NUnit.

**Comment by freeranger** [comment]
Why do this - do we get any benefit from it?

**Comment by PureKrome** [comment]
- modernizing the tech stack
- more people these days should be more familiar with xunit over nunit == easier and greater chance of contributor uptake
- consistency : common tech stack used in modern repo's.

**Comment by freeranger** [comment]
I don't know that you can say more people are familiar with xUnit over NUnit - drawing on my own experiences and the network of developers I know, NUnit is by far and away the most popular still.  Indeed I personally don't know anyone actively using xUnit and have rarely seen a github project using it - that is not to say there aren't shed loads of course, just that my experience doesn't suggest xUnit is more popular.

If you look at what is apparently the top 20 nuget packages for unit testing: http://nugetmusthaves.com/Category/Unit%20Testing

* moq - xUnit
* nsubstitute - NUnit
* fluent assertions - MsTest
* true fake - not sure but their examples use NUnit
* NUnit - guess :)
* fake it easy - xUnit
* fsunit - NUnit, MbUnit, xUnit, and MsTest (though weirdly it has a dependency on NUnit only)
* nbuilder - NUnit
* Flurl.Http - NUnit
* OpenConver - NUnit
* RhinoMocks - xUnit
* Chutzpah - xUnit
* Chill BDD - xUnit
* MyTested.AspNetCore.Mvc.Licensing + 4 others from the same guy- xUnit
* ReportGenerator - MsTest
* dotMemoryUnit - not sure but their open source TC plugin for it and other .net projects use NUnit

So in total we have:
MSTest - 3
NUnit - 8
xUnit - 11

This is counting fsunit as MSTest, NUnit and XUnit, and if you consider 5 of them are by the same guy, essentially one project split into loads of components it seems, then that's 7 "unique" projects for xUnit - so really there's nothing in it, usage is about the same.  I have to confess I am surprised xUnit is so high given my own experiences but there you go - the point being there is no clear winner.

I'm not adverse to change, just not change for change sake, which is what this feels like tbh.

Do you have any particular reason to think there are not more contributors to the project simply because it uses NUnit rather than xUnit?

If you have capacity to put some effort into this project then perhaps adding source map support would be a better use of time than this?  After all, most people will be consumers of the project rather than contributors to it and I think lack of source map support will hurt it more than any other single factor.

Once again though, your project so your decision ultimately...

**Comment by PureKrome** [comment]
> NUnit is by far and away the most popular still

.NET vNext is all xUnit: [source](https://github.com/aspnet/Home/wiki/Engineering-guidelines#unit-tests)

I've also not seen a repo with nUnit for .. well.. ages. I'm not an enterprise dev, though.
If .NET vnext is pushing xunit as their default, rest assured a majority of devs will also follow.

>  I have to confess I am surprised xUnit is so high

Again, refer to more recent repo's these days + .NET vnext/future.

> just not change for change sake

Agreed - I've got better things to do with my time :)

> Do you have any particular reason to think there are not more contributors to the project simply because it uses NUnit rather than xUnit?

It's about familiarity and consistency. This (I would hope) lowers the barrier to entry for helping.

> If you have capacity to put some effort into this project then perhaps adding source map support would be a better use of time than this?

Agreed completely 👍 . But .. this capacity requires brain power which I don't have much left for this project, especially since it's been for-ever since I've even used this. As opposed to the brain-effort required to migrate to xUnit, wire up AppVeyor support and split this into repo's and consistent layout/structure ... though mind numbing, it's more labour than brain-effort.

>  After all, most people will be consumers of the project rather than contributors to it and I think lack of source map support will hurt it more than any other single factor.

Yep - couldn't agree more. But refer to previous comment

**Comment by freeranger** [comment]
That list I referenced has votes cast this month, so pretty recent :)

MS Used to use MsTest but I didn't see everyone flocking to that, so I'm not sure that argument holds water :)

It still feels like change for change sake - I haven't seen any compelling reason to switch but hey it's your time to waste not mine :)

**Comment by PureKrome** [comment]
Closing this cause I can't be bothered, basically. If I was working with this library on a more regular basis, then I would. 🥂
